name: Deploy Cloud Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_POOL_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy The Slashinator Cloud Function
        id: deploy
        shell: bash
        run: |
          gcloud functions deploy the-slashinator \
            --runtime=nodejs20 \
            --no-gen2 \
            --entry-point=slashinator \
            --region=europe-west1 \
            --update-labels=env=production,team=thoughtgears,app=the-slashinator,owner=thoughtgears \
            --project=${{ secrets.PROJECT_ID }} \
            --service-account=${{ secrets.APP_SERVICE_ACCOUNT }} \
            --trigger-topic=${{ secrets.PUBSUB_TOPIC }} \
            --quiet
